#############################################################################
# Makefile for building: RtspPlayerFfmpeg.app/Contents/MacOS/RtspPlayerFfmpeg
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  RtspPlayerFfmpeg.pro
# Template: app
# Command: /Users/taiguangyin/Qt/5.9.1/clang_64/bin/qmake -o Makefile RtspPlayerFfmpeg.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/usr/bin/gcc
CXX           = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I../../../Qt/5.9.1/clang_64/lib/QtMultimediaWidgets.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtMultimedia.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.9.1/clang_64/mkspecs/macx-g++ -F/Users/taiguangyin/Qt/5.9.1/clang_64/lib
QMAKE         = /Users/taiguangyin/Qt/5.9.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/taiguangyin/Qt/5.9.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/taiguangyin/Qt/5.9.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RtspPlayerFfmpeg1.0.0
DISTDIR = /Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/.tmp/RtspPlayerFfmpeg1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/usr/bin/g++
LFLAGS        = -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/taiguangyin/Qt/5.9.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/taiguangyin/Qt/5.9.1/clang_64/lib /Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/libs/libavcodec.58.dylib /Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/libs/libavdevice.58.dylib /Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/libs/libavfilter.7.dylib /Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/libs/libavformat.58.dylib /Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/libs/libavutil.56.dylib /Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/libs/libpostproc.55.dylib /Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/libs/libswresample.3.dylib /Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/libs/libswscale.5.dylib -framework QtMultimediaWidgets -framework QtMultimedia -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		videoplayer.cpp \
		localvdeoplayer.cpp \
		videowindow.cpp moc_mainwindow.cpp \
		moc_videoplayer.cpp \
		moc_localvideoplayer.cpp \
		moc_videowindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		videoplayer.o \
		localvdeoplayer.o \
		videowindow.o \
		moc_mainwindow.o \
		moc_videoplayer.o \
		moc_localvideoplayer.o \
		moc_videowindow.o
DIST          = ../../../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/g++-macx.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/macx-g++/qmake.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		RtspPlayerFfmpeg.pro mainwindow.h \
		videoplayer.h \
		localvideoplayer.h \
		videowindow.h main.cpp \
		mainwindow.cpp \
		videoplayer.cpp \
		localvdeoplayer.cpp \
		videowindow.cpp
QMAKE_TARGET  = RtspPlayerFfmpeg
DESTDIR       = 
TARGET        = RtspPlayerFfmpeg.app/Contents/MacOS/RtspPlayerFfmpeg

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_videowindow.h $(OBJECTS)  
	@test -d RtspPlayerFfmpeg.app/Contents/MacOS/ || mkdir -p RtspPlayerFfmpeg.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RtspPlayerFfmpeg.pro ../../../Qt/5.9.1/clang_64/mkspecs/macx-g++/qmake.conf ../../../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/common/g++-macx.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/macx-g++/qmake.conf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.9.1/clang_64/mkspecs/features/lex.prf \
		RtspPlayerFfmpeg.pro \
		../../../Qt/5.9.1/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.9.1/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile RtspPlayerFfmpeg.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../Qt/5.9.1/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.9.1/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.9.1/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.9.1/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/g++-base.conf:
../../../Qt/5.9.1/clang_64/mkspecs/common/g++-macx.conf:
../../../Qt/5.9.1/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.9.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.9.1/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.9.1/clang_64/mkspecs/macx-g++/qmake.conf:
../../../Qt/5.9.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.9.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.9.1/clang_64/mkspecs/features/lex.prf:
RtspPlayerFfmpeg.pro:
../../../Qt/5.9.1/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl:
../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.9.1/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
../../../Qt/5.9.1/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.9.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../Qt/5.9.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile RtspPlayerFfmpeg.pro -spec macx-g++ CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

RtspPlayerFfmpeg.app/Contents/PkgInfo: 
	@test -d RtspPlayerFfmpeg.app/Contents || mkdir -p RtspPlayerFfmpeg.app/Contents
	@$(DEL_FILE) RtspPlayerFfmpeg.app/Contents/PkgInfo
	@echo "APPL????" > RtspPlayerFfmpeg.app/Contents/PkgInfo
RtspPlayerFfmpeg.app/Contents/Resources/empty.lproj: 
	@test -d RtspPlayerFfmpeg.app/Contents/Resources || mkdir -p RtspPlayerFfmpeg.app/Contents/Resources
	@touch RtspPlayerFfmpeg.app/Contents/Resources/empty.lproj
	
RtspPlayerFfmpeg.app/Contents/Info.plist: 
	@test -d RtspPlayerFfmpeg.app/Contents || mkdir -p RtspPlayerFfmpeg.app/Contents
	@$(DEL_FILE) RtspPlayerFfmpeg.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.RtspPlayerFfmpeg,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,RtspPlayerFfmpeg,g" -e "s,@LIBRARY@,RtspPlayerFfmpeg,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.9.1/clang_64/mkspecs/macx-g++/Info.plist.app >RtspPlayerFfmpeg.app/Contents/Info.plist

all: Makefile \
		RtspPlayerFfmpeg.app/Contents/PkgInfo \
		RtspPlayerFfmpeg.app/Contents/Resources/empty.lproj \
		RtspPlayerFfmpeg.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h videoplayer.h localvideoplayer.h videowindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp videoplayer.cpp localvdeoplayer.cpp videowindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui videowindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r RtspPlayerFfmpeg.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/usr/bin/g++ -pipe -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.9.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_videoplayer.cpp moc_localvideoplayer.cpp moc_videowindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_videoplayer.cpp moc_localvideoplayer.cpp moc_videowindow.cpp
moc_mainwindow.cpp: ../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QtDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		videoplayer.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		localvideoplayer.h \
		mainwindow.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/taiguangyin/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/taiguangyin/Qt/5.9.1/clang_64/mkspecs/macx-g++ -I/Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg -I/Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/include -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtMultimedia.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/taiguangyin/Qt/5.9.1/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_videoplayer.cpp: ../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		videoplayer.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/taiguangyin/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/taiguangyin/Qt/5.9.1/clang_64/mkspecs/macx-g++ -I/Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg -I/Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/include -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtMultimedia.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/taiguangyin/Qt/5.9.1/clang_64/lib videoplayer.h -o moc_videoplayer.cpp

moc_localvideoplayer.cpp: ../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		localvideoplayer.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/taiguangyin/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/taiguangyin/Qt/5.9.1/clang_64/mkspecs/macx-g++ -I/Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg -I/Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/include -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtMultimedia.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/taiguangyin/Qt/5.9.1/clang_64/lib localvideoplayer.h -o moc_localvideoplayer.cpp

moc_videowindow.cpp: ../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		videowindow.h \
		moc_predefs.h \
		../../../Qt/5.9.1/clang_64/bin/moc
	/Users/taiguangyin/Qt/5.9.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/taiguangyin/Qt/5.9.1/clang_64/mkspecs/macx-g++ -I/Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg -I/Users/taiguangyin/gytai/QT/RtspPlayerFfmpeg/include -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtMultimedia.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtGui.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtNetwork.framework/Headers -I/Users/taiguangyin/Qt/5.9.1/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/Users/taiguangyin/Qt/5.9.1/clang_64/lib videowindow.h -o moc_videowindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_videowindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_videowindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/5.9.1/clang_64/bin/uic
	/Users/taiguangyin/Qt/5.9.1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_videowindow.h: videowindow.ui \
		../../../Qt/5.9.1/clang_64/bin/uic
	/Users/taiguangyin/Qt/5.9.1/clang_64/bin/uic videowindow.ui -o ui_videowindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QtDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		videoplayer.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		localvideoplayer.h \
		videowindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QTextCodec \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qtextcodec.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QtDebug \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		videoplayer.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		localvideoplayer.h \
		ui_mainwindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QtMath \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

videoplayer.o: videoplayer.cpp videoplayer.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		include/libavcodec/avcodec.h \
		include/libavutil/samplefmt.h \
		include/libavutil/avutil.h \
		include/libavutil/common.h \
		include/libavutil/attributes.h \
		include/libavutil/macros.h \
		include/libavcodec/version.h \
		include/libavutil/version.h \
		include/libavutil/avconfig.h \
		include/libavutil/mem.h \
		include/libavutil/error.h \
		include/libavutil/rational.h \
		include/libavutil/mathematics.h \
		include/libavutil/intfloat.h \
		include/libavutil/log.h \
		include/libavutil/pixfmt.h \
		include/libavutil/buffer.h \
		include/libavutil/cpu.h \
		include/libavutil/channel_layout.h \
		include/libavutil/dict.h \
		include/libavutil/frame.h \
		include/libavutil/hwcontext.h \
		include/libavformat/avformat.h \
		include/libavformat/avio.h \
		include/libavformat/version.h \
		include/libswscale/swscale.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videoplayer.o videoplayer.cpp

localvdeoplayer.o: localvdeoplayer.cpp localvideoplayer.h \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/QThread \
		../../../Qt/5.9.1/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/QImage \
		../../../Qt/5.9.1/clang_64/lib/QtGui.framework/Headers/qimage.h \
		include/libavcodec/avcodec.h \
		include/libavutil/samplefmt.h \
		include/libavutil/avutil.h \
		include/libavutil/common.h \
		include/libavutil/attributes.h \
		include/libavutil/macros.h \
		include/libavcodec/version.h \
		include/libavutil/version.h \
		include/libavutil/avconfig.h \
		include/libavutil/mem.h \
		include/libavutil/error.h \
		include/libavutil/rational.h \
		include/libavutil/mathematics.h \
		include/libavutil/intfloat.h \
		include/libavutil/log.h \
		include/libavutil/pixfmt.h \
		include/libavutil/buffer.h \
		include/libavutil/cpu.h \
		include/libavutil/channel_layout.h \
		include/libavutil/dict.h \
		include/libavutil/frame.h \
		include/libavutil/hwcontext.h \
		include/libavformat/avformat.h \
		include/libavformat/avio.h \
		include/libavformat/version.h \
		include/libswscale/swscale.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o localvdeoplayer.o localvdeoplayer.cpp

videowindow.o: videowindow.cpp videowindow.h \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.9.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_videowindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videowindow.o videowindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_videoplayer.o: moc_videoplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videoplayer.o moc_videoplayer.cpp

moc_localvideoplayer.o: moc_localvideoplayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_localvideoplayer.o moc_localvideoplayer.cpp

moc_videowindow.o: moc_videowindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videowindow.o moc_videowindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

